version: "3"
services:
  nginx:
    container_name: nginx-server
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodeapp
  nodeapp:
    container_name: nodeapp
    restart: always
    build: .
    command: ["node", "index.js"]
    environment:
      - NODE_ENV=production
      - RHOST=redis
    ports:
      - "3000:3000"
    networks:
      - redis-net
    depends_on:
      - mongo-server
      - redis
  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis-server:
    image: 'redis'
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    network_mode: host
    networks:
      - redis-net
    volumes:
      - redis-data:/data
networks:
  redis-net:

volumes:
  redis-data:
